resolver: lts-13.4
packages:
- .
extra-deps:
# Pinning to a commit due to https://github.com/dhall-lang/dhall-haskell/issues/788
#- dhall-1.20.1
#- dhall-json-1.2.6
- git: https://github.com/dhall-lang/dhall-haskell
  commit: 095ee6db61f858acd5ff04fddabc7dfcca6be365
  subdirs:
  - dhall
  - dhall-json
- fgl-5.7.0.1
# Waiting for a release with the new base upper bounds
#- async-pool-0.9.0.2
- git: https://github.com/f-f/async-pool
  commit: 5f5635af5061ada0498fd04482efbab328c4775b
- Win32-2.5.4.1@sha256:e623a1058bd8134ec14d62759f76cac52eee3576711cb2c4981f398f1ec44b85
